sudo: false
services: docker
language: cpp

jobs:
  include:
    - stage: build
      script:
        - docker build -t tylern4/hipo2root . -f Dockerfile
        - wget -q http://stash.osgconnect.net/~tylern/clas12/hipo/v1/5bp6p1/skim4_4020.hipo
        - docker run -v $PWD:/tmp tylern4/hipo2root skim4_4020.hipo
        - du -sh skim4_4020.*
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker images -a
        - docker push tylern4/hipo2root
